"""items table

Revision ID: b4aa1ef34c99
Revises: 4f40ba149e7f
Create Date: 2020-07-17 18:27:53.968226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aa1ef34c99'
down_revision = '4f40ba149e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('bought', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_item_name'), 'item', ['item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_name'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
