"""item name not unique

Revision ID: db6d68a459da
Revises: b4aa1ef34c99
Create Date: 2020-07-28 19:55:57.167019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6d68a459da'
down_revision = 'b4aa1ef34c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_item_name', table_name='item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_item_item_name', 'item', ['item_name'], unique=1)
    # ### end Alembic commands ###
